#!/usr/bin/env bash
# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}"
cd localdata
HOST=${1:-"https://prow.k8s.io"}
if [[ "${HOST}" == "openshift" ]]; then
	HOST="https://deck-ci.svc.ci.openshift.org"
fi

echo "fetching localdata from ${HOST}"
curl "${HOST}/prowjobs.js" > prowjobs.json
curl "${HOST}/tide.js?var=tideData" > tide.js
curl "${HOST}/tide-history.js?var=tideHistory" > tide-history.js
curl "${HOST}/plugin-help.js?var=allHelp" > plugin-help.js
curl "${HOST}/pr-data.js" > pr-data.js

bazel run //prow/cmd/deck:deck -- \
  --pregenerated-data=${DIR}/localdata \
  --static-files-location=./prow/cmd/deck/static \
  --template-files-location=./prow/cmd/deck/template \
  --spyglass-files-location=./prow/spyglass/lenses \
  --config-path "${DIR}/../../../config/prow/config.yaml" \
  --spyglass \
  --gcs-no-auth
