# Copyright 2021 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from build_grid import build_test

# A map of distro names as used in the job name to
# distro names recognized by build_test.
# TODO(rifelpet): Use build-grid's distro_options
# (it would change the job names and lose history)
distros = {
  'debian9': 'deb9',
  'debian10': 'deb10',
  'ubuntu1804': 'u1804',
  'ubuntu2004': 'u2004',
  'centos7': 'centos7',
  'centos8': 'centos8',
  'amazonlinux2': 'amzn2',
  'rhel7': 'rhel7',
  'rhel8': 'rhel8',
  'flatcar': 'flatcar'
}

print("# Test scenarios generated by build_distros.py (do not manually edit)")
print("periodics:")
for distro, distro_name in distros.items():
  build_test(
    distro=distro_name,
    networking='calico',
    container_runtime='containerd',
    k8s_version='stable',
    name_override='kops-aws-distro-image' + distro,
    extra_dashboards=['kops-distros'],
    interval='8h',
    skip_override=r'\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|RuntimeClass|RuntimeHandler'
  )
