presets:
- labels:
    preset-storage-e2e-service-account: "true"
  env:
  # storage e2e tests borrow this as a preconfigured key instead of creating and
  # injecting a new key. this allows us to avoid mass key download warnings
  - name: E2E_GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/service-account.json
  volumes:
  - name: service
    secret:
      secretName: service-account
  volumeMounts:
  - name: service
    mountPath: /etc/service-account
    readOnly: true

- labels:
    preset-kops-azure-cred-wi: "true"
  env: # below env values are not secrets
    - name: AZURE_CLIENT_ID # AZURE_CLIENT_ID is being overloaded with Azure Workload ID
      value: "34d8e06d-d198-477e-b166-6936e58d90ae"
    - name: AZURE_SUBSCRIPTION_ID
      value: "46678f10-4bbb-447e-98e8-d2829589f2d8"
    - name: AZURE_TENANT_ID
      value: "d1aa7522-0959-442e-80ee-8c4f7fb4c184"
    - name: AZURE_FEDERATED_TOKEN_FILE
      value: "/var/run/secrets/azure-token/serviceaccount/token"
  volumes:
    - name: azure-token
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 86400
              path: token
              audience: api://AzureADTokenExchange
  volumeMounts:
    - mountPath: /var/run/secrets/azure-token/serviceaccount
      name: azure-token
      readOnly: true
