periodics:
- name: ci-contributor-site-update-hugo-modules
  interval: 24h
  annotations:
    testgrid-dashboards: sig-contribex-contributor-website
    testgrid-tab-name: ci-contributor-site-update-hugo-modules
    testgrid-alert-email: sig-contribex-leads@kubernetes.io
    testgrid-num-failures-to-alert: "3"
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: contributor-site
    base_ref: master
  spec:
    containers:
    - image: us-central1-docker.pkg.dev/k8s-staging-images/contributor-site/k8s-contrib-site-hugo:v0.133.0-7f658d63039e
      command:
      - bash
      args:
      - ./hack/update-hugo-modules.sh
      env:
      - name: GITHUB_TOKEN_PATH
        value: /etc/github-token/oauth
      - name: GOMODCACHE
        value: /tmp/gomod
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
    volumes:
    - name: github
      secret:
        secretName: k8s-ci-robot-github-token
