periodics:
- name: ci-contributor-site-update-hugo-modules
  interval: 24h # Daily
  annotations:
    testgrid-dashboards: sig-contribex-contributor-website
    testgrid-tab-name: ci-contributor-site-update-hugo-modules
    testgrid-alert-email: sig-contribex-leads@kubernetes.io
    testgrid-num-failures-to-alert: "3"
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: contributor-site
    base_ref: master
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20260410-1226423a7b-master
      command:
      - runner.sh
      args:
      - ./hack/update-hugo-modules.sh
      env:
      - name: GITHUB_TOKEN_PATH
        value: /etc/github-token/oauth
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 256Mi
    volumes:
    - name: github
      secret:
        secretName: k8s-ci-robot-github-token
