/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package config defines the static test suite, job, and infrastructure
// configurations for Kubernetes GCE COS e2e test generation.
package config

import "k8s.io/test-infra/releng/generate-tests/internal/types"

const (
	// DefaultImage is the kubekins-e2e container image used by generated jobs.
	// This value is automatically updated by the image bumper.
	DefaultImage = "gcr.io/k8s-staging-test-infra/kubekins-e2e:v20260205-38cfa9523f-master"

	// GCSLogPrefix is the GCS bucket prefix for job logs.
	GCSLogPrefix = "kubernetes-ci-logs/logs/"

	// Comment is the header comment for generated files.
	Comment = "AUTO-GENERATED by releng/generate-tests - DO NOT EDIT."

	// Cluster is the Prow build cluster for generated jobs.
	Cluster = "k8s-infra-prow-build"

	// Timeout constants for test suites (in minutes).
	timeoutAlphafeatures = 180
	timeoutDefault       = 120
	timeoutReboot        = 180
	timeoutSerial        = 660
	timeoutSlow          = 150

	// NumFailuresToAlert is the default num-failures-to-alert for informing jobs.
	NumFailuresToAlert = 6

	// FilePermissions is the file mode for generated output files.
	FilePermissions = 0o644
)

// Long test_args strings extracted as constants for line length compliance.
const (
	alphaFeaturesTestArgs = `--test_args=--ginkgo.focus=\[Feature:(AdmissionWebhookMatchConditions|InPlacePodVerticalScaling|SidecarContainers|StorageVersionAPI|PodPreset|StatefulSetAutoDeletePVC)\]|Networking --ginkgo.skip=\[Feature:(SCTPConnectivity|Volumes|Networking-Performance|Example)\]|IPv6|csi-hostpath-v0 --minStartupPods=8`
	defaultTestArgs       = `--test_args=--ginkgo.skip=\[Driver:.gcepd\]|\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8`
	serialTestArgs        = `--test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Driver:.gcepd\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8`
	slowTestArgs          = `--test_args=--ginkgo.focus=\[Slow\] --ginkgo.skip=\[Driver:.gcepd\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:([^L].*|L[^o].*|Lo[^a].*|Loa[^d].*)\] --minStartupPods=8`
	serialOverrideArgs    = `--test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Driver:.gcepd\]|\[Flaky\]|\[Feature:.+\]|\[sig-cloud-provider-gcp\] --minStartupPods=8`
)

// GetDefaultResources returns the default CPU/memory for job containers.
func GetDefaultResources() types.ProwResourceValues {
	return types.ProwResourceValues{CPU: "1000m", Memory: "3Gi"}
}

// TestSuiteConfig defines a test suite's static configuration.
type TestSuiteConfig struct {
	Args      []string
	Timeout   int // in minutes
	Cluster   string
	Resources types.ProwResourceValues
}

// JobConfig defines a job's per-tier and per-suite properties.
type JobConfig struct {
	Suite              string
	ReleaseBlocking    bool
	ReleaseInforming   bool
	NumFailuresToAlert int // 0 means not set
	OverrideArgs       []string
	TestSuiteOverride  string // override test suite name
}

// CloudProviderArgs returns the GCE cloud provider arguments.
func CloudProviderArgs() []string {
	return []string{
		"--check-leaked-resources",
		"--provider=gce",
		"--gcp-region=us-central1",
	}
}

// ImageArgs returns the COS image arguments.
func ImageArgs() []string {
	return []string{
		"--gcp-node-image=gci",
	}
}

// TestSuites returns the static test suite configurations.
func TestSuites() map[string]TestSuiteConfig {
	defaultResources := GetDefaultResources()

	return map[string]TestSuiteConfig{
		"alphafeatures-eventedpleg": {
			Args: []string{
				"--timeout=180m",
				"--env=ENABLE_POD_PRIORITY=true",
				"--env=KUBE_FEATURE_GATES=AllAlpha=true,AllBeta=true,EventedPLEG=false",
				"--env=ENABLE_CACHE_MUTATION_DETECTOR=true",
				"--runtime-config=api/all=true",
				alphaFeaturesTestArgs,
			},
			Timeout:   timeoutAlphafeatures,
			Cluster:   Cluster,
			Resources: defaultResources,
		},
		"default": {
			Args: []string{
				"--timeout=120m",
				defaultTestArgs,
				"--ginkgo-parallel=30",
				"--env=ENABLE_CACHE_MUTATION_DETECTOR=true",
			},
			Timeout:   timeoutDefault,
			Cluster:   Cluster,
			Resources: types.ProwResourceValues{CPU: "2000m", Memory: "6Gi"},
		},
		"reboot": {
			Args: []string{
				"--timeout=180m",
				`--test_args=--ginkgo.focus=\[Feature:Reboot\] --minStartupPods=8`,
			},
			Timeout:   timeoutReboot,
			Cluster:   Cluster,
			Resources: defaultResources,
		},
		"serial": {
			Args: []string{
				"--timeout=660m",
				serialTestArgs,
				"--ginkgo-parallel=1",
			},
			Timeout:   timeoutSerial,
			Cluster:   Cluster,
			Resources: defaultResources,
		},
		"slow": {
			Args: []string{
				"--timeout=150m",
				slowTestArgs,
				"--ginkgo-parallel=30",
			},
			Timeout:   timeoutSlow,
			Cluster:   Cluster,
			Resources: types.ProwResourceValues{CPU: "1000m", Memory: "6Gi"},
		},
	}
}

// Jobs returns the job configurations for each test suite.
// The serial suite has a job-level override that adds
// |\[sig-cloud-provider-gcp\] to the skip pattern.
func Jobs() []JobConfig {
	return []JobConfig{
		{
			Suite:              "alphafeatures",
			ReleaseBlocking:    true,
			ReleaseInforming:   false,
			NumFailuresToAlert: 0,
			OverrideArgs:       nil,
			TestSuiteOverride:  "alphafeatures-eventedpleg",
		},
		{
			Suite:              "default",
			ReleaseBlocking:    true,
			ReleaseInforming:   false,
			NumFailuresToAlert: 0,
			OverrideArgs:       nil,
			TestSuiteOverride:  "",
		},
		{
			Suite:              "reboot",
			ReleaseBlocking:    true,
			ReleaseInforming:   false,
			NumFailuresToAlert: 0,
			OverrideArgs:       nil,
			TestSuiteOverride:  "",
		},
		{
			Suite:              "serial",
			ReleaseBlocking:    false,
			ReleaseInforming:   true,
			NumFailuresToAlert: NumFailuresToAlert,
			OverrideArgs:       []string{serialOverrideArgs},
			TestSuiteOverride:  "",
		},
		{
			Suite:              "slow",
			ReleaseBlocking:    false,
			ReleaseInforming:   true,
			NumFailuresToAlert: NumFailuresToAlert,
			OverrideArgs:       nil,
			TestSuiteOverride:  "",
		},
	}
}
