presubmits:
  kubernetes-sigs/provider-ibmcloud-test-infra:
  - name: pull-provider-ibmcloud-test-infra-kubernetes
    cluster: k8s-infra-ppc64le-prow-build
    always_run: false
    decorate: true
    decoration_config:
      timeout: 220m
    annotations:
      description: Optional presubmit job to test changes in kubernetes-sigs/provider-ibmcloud-test-infra repo
      testgrid-dashboards: ibm-ppc64le-presubmits
      testgrid-tab-name: pull-provider-ibmcloud-test-infra-kubernetes
    labels:
      preset-ibmcloud-cred: "true"
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260629-f759c32706-master
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 2
              memory: "10Gi"
            limits:
              cpu: 2
              memory: "10Gi"
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              "./scripts/updown-ibmcloud.sh"

  - name: pull-provider-ibmcloud-test-infra-kubetest2-secretmanager-build
    cluster: k8s-infra-ppc64le-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 30m
    annotations:
      testgrid-dashboards: ibm-ppc64le-presubmits
      testgrid-tab-name: kubetest2-tf-secretmanager-build
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260629-f759c32706-master
          command:
            - runner.sh
          args:
            - make
            - build-deployer-tf
            - build-secret-manager
          resources:
            requests:
              cpu: 1
              memory: "2Gi"
            limits:
              cpu: 1
              memory: "2Gi"
