presubmits:
  kubernetes-sigs/provider-ibmcloud-test-infra:
  - name: pull-provider-ibmcloud-test-infra-kubernetes
    cluster: k8s-infra-ppc64le-prow-build
    always_run: false
    decorate: true
    decoration_config:
      timeout: 220m
    annotations:
      description: Optional presubmit job to test changes in kubernetes-sigs/provider-ibmcloud-test-infra repo
      testgrid-dashboards: ibm-ppc64le-presubmits
      testgrid-tab-name: pull-provider-ibmcloud-test-infra-kubernetes
    labels:
      preset-ibmcloud-cred: "true"
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260504-c27e3ff179-master
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 2
              memory: "10Gi"
            limits:
              cpu: 2
              memory: "10Gi"
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              set -o xtrace

              # Build the kubetest2 tf deployer locally and source the other dependencies.
              OUT_DIR=/go/bin WHAT='terraform' make build-deployer-tf download-from-cos
              make download-tf-plugins-from-cos
              make install-ansible

              K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/k8s-release-dev/ci/latest.txt)

              kubetest2 tf --powervs-image-name CentOS-Stream-10 \
                --powervs-ssh-key k8s-prow-sshkey \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --build-version $K8S_BUILD_VERSION \
                --release-marker $K8S_BUILD_VERSION \
                --cluster-name pull-$(date +%s) \
                --workers-count 1 \
                --up --down --auto-approve --retry-on-tf-failure 3 --ignore-destroy-errors \
                --break-kubetest-on-upfail true \
                --powervs-memory 8 --powervs-processors 0.25 \
                --test=ginkgo -- --parallel 30 --test-package-dir ci --test-package-version $K8S_BUILD_VERSION --focus-regex='Pods should be submitted and removed'

  - name: pull-provider-ibmcloud-test-infra-kubetest2-secretmanager-build
    cluster: k8s-infra-ppc64le-prow-build
    always_run: true
    decorate: true
    decoration_config:
      timeout: 30m
    annotations:
      testgrid-dashboards: ibm-ppc64le-presubmits
      testgrid-tab-name: kubetest2-tf-secretmanager-build
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260504-c27e3ff179-master
          command:
            - runner.sh
          args:
            - make
            - build-deployer-tf
            - build-secret-manager
          resources:
            requests:
              cpu: 1
              memory: "2Gi"
            limits:
              cpu: 1
              memory: "2Gi"
