#!/bin/bash

# A script that uses configurator to create a YAML file, and then pushes that
# YAML file to k8s/test-infra's config/testgrids directory
#
# Used by teams that host different instances of Prow, but want to show their
# results on testgrid.k8s.io
#

set -o errexit
set -o nounset
set -o pipefail

main() {
  branch="transfigure-branch"

  if [[ $# -lt 1 ]]; then
      echo "Usage: $(basename "$0") </path/to/github/token> [prow_config] [prow-job_config] [testgrid-yaml] [subdir-path]" >&2
      echo "Path to GitHub token required" >&2
      exit 1
  fi

  token=$(readlink -f "$1")
  shift
  user-from-token
  ensure-git-config
  parse-args "$@"

  echo "Ensuring kubernetes/test-infra repo"
  if [[ -d test-infra ]]; then
    echo "Directory 'test-infra' found; using as kubernetes/test-infra repository"
  else
    #TODO(chases2): Clone only the test-infra/config/testgrids subdirectory used
    git clone https://github.com/kubernetes/test-infra.git
    trap "cleanup-repository" EXIT
    echo "Created temporary repository"
  fi

  k8s_repo=$(readlink -f test-infra)
  testgrid_dir=$(readlink -f "test-infra/config/testgrids")

  echo "Checking out ${branch}"
  cd "${k8s_repo}"
  git checkout -B "${branch}"

  echo "Generating testgrid yaml"
  go run k8s.io/test-infra/testgrid/cmd/configurator \
    --prow-config "${prow_config}" \
    --prow-job-config "${job_config}" \
    --output-yaml \
    --yaml "${testgrid_config}" \
    --oneshot \
    --output "${testgrid_dir}/${testgrid_subdir}/gen-config.yaml"

  git add --all

  if ! git diff --quiet ; then
    echo "Transfigure did not change anything. Aborting no-op bump"
    exit 0
  fi

  title="Update TestGrid for ${testgrid_subdir}"
  git commit -m "${title}"
  echo "Pushing commit to ${user}/${remote_fork_repo}:${branch}..."
  git push -f "https://${user}:$(cat "${token}")@github.com/${user}/${remote_fork_repo}" "HEAD:${branch}"

  echo "Creating PR to merge ${user}:${branch} into k8s/test-infra:master..."
  go run k8s.io/test-infra/robots/pr-creator \
    --github-token-path="${token}" \
    --org="kubernetes" --repo="test-infra" --branch=master \
    --title="${title}" --match-title="${title}" \
    --body="Generated by transfigure.sh" \
    --source="${user}:${branch}" \
    --confirm

  echo "PR created successfully!"
  return 0
}

parse-args() {
  prow_config="${CONFIG_PATH:-$1}"
  job_config="${JOB_CONFIG_PATH:-$2}"
  testgrid_config="${TESTGRID_CONFIG:-$3}"
  testgrid_subdir="${ORG_REPO:-$4}"
  remote_fork_repo="${FORK_GH_REPO:-"test-infra"}"
}

user-from-token() {
  user=$(curl -H "Authorization: token $(cat "${token}")" "https://api.github.com/user" 2>/dev/null | sed -n "s/\s\+\"login\": \"\(.*\)\",/\1/p")
}

cleanup-repository() {
  echo "Cleaning temporary repository at ${k8s_repo}"
  cd ..
  rm -rf "${k8s_repo}"
}

ensure-git-config() {
  git config user.name &>/dev/null && git config user.email &>/dev/null && return 0
  echo "ERROR: git config user.name, user.email unset. No defaults provided" >&2
  return 1
}

main "$@"
