# sigs.k8s.io/scheduler-library presubmits
presubmits:
  kubernetes-sigs/scheduler-library:
  - name: pull-scheduler-library-verify-main
    decorate: true
    path_alias: sigs.k8s.io/scheduler-library
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-scheduler-library-verify-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260504-c27e3ff179-master
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "2"
        command:
        - runner.sh
        args:
        - make
        - verify
