# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM google/debian:jessie
MAINTAINER Chao Xu <xuchao@google.com>
RUN apt-get update
RUN apt-get install -y -qq ca-certificates git wget
RUN wget https://storage.googleapis.com/golang/go1.7.5.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.7.5.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"

ENV GOPATH=/
RUN go get github.com/tools/godep
WORKDIR "/src/github.com/tools/godep"
RUN git checkout tags/v75
RUN go install ./... 
WORKDIR "/"

CMD ["/mungegithub", "--dry-run", "--token-file=/token"]

ADD mungegithub /mungegithub
ADD mungers/publish_scripts/clientgo_publish.sh /publish_scripts/clientgo_publish.sh
ADD mungers/publish_scripts/apimachinery_sync_from_kubernetes.sh /publish_scripts/apimachinery_sync_from_kubernetes.sh
