#!/usr/bin/env bash
# Copyright 2023 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")"

if ((BASH_VERSINFO[0] < 4)); then
    echo "At least bash version 4 is required to run this script"
    exit 1
fi

# Change the following configurations to adapt the resulting ignitions files.
declare -A CONFIGURATIONS=(
    ["crio"]="root env"
    ["crio_eventedpleg"]="root env eventedpleg"
    ["crio_canary"]="root env-canary"
    ["crio_drop_infra_ctr"]="root env drop-infra-ctr"
    ["crio_swap1g"]="root env swap-1G"
    ["crio_imagefs"]="root env imagefs"
    ["crio_splitfs"]="root env splitfs"
    ["crio_hugepages"]="root env hugepages"
    ["crio_userns"]="root env-canary userns crun-enabled"
)

CONTAINER_RUNTIME=$(which podman 2>/dev/null) ||
    CONTAINER_RUNTIME=$(which nerdctl 2>/dev/null) ||
    CONTAINER_RUNTIME=$(which docker 2>/dev/null)

if [[ -z "$CONTAINER_RUNTIME" ]]; then
    echo "Neither podman, nerdctl nor docker found in \$PATH"
    exit 1
fi

YQ_IMAGE=mikefarah/yq:4
BUTANE_IMAGE=quay.io/coreos/butane:release
BASE_PATH=base

# Pull the latest image version
for IMAGE in $YQ_IMAGE $BUTANE_IMAGE; do
    $CONTAINER_RUNTIME pull "$IMAGE"
done

merge() {
    ARGS=()
    for ARG in "${@:2}"; do
        ARGS+=("$BASE_PATH/$ARG.yaml")
    done

    set -x
    # shellcheck disable=SC2016
    $CONTAINER_RUNTIME run --privileged -i --rm -v "$PWD":/w -w /w $YQ_IMAGE \
        ea '. as $item ireduce ({}; . *+ $item)' "${ARGS[@]}" >"$1.yaml"
    { set +x; } 2>/dev/null
}

for i in "${!CONFIGURATIONS[@]}"; do
    echo "Building ${i}"

    IFS=' ' read -r -a ARGS <<<"${CONFIGURATIONS[$i]}"
    merge "$i" "${ARGS[@]}"

    set -x
    $CONTAINER_RUNTIME run --privileged -i --rm -v "$PWD":/w -w /w $BUTANE_IMAGE \
        -ps -d $BASE_PATH <"$i.yaml" >../"$i.ign"
    { set +x; } 2>/dev/null
done

CRIO_SCRIPT_COMMIT=$(grep "CRIO_SCRIPT_COMMIT" "$BASE_PATH/env.yaml" | sed -rn 's/^.*CRIO_SCRIPT_COMMIT=([0-9a-f]+).*$/\1/p')
CRIO_SCRIPT_URL="https://raw.githubusercontent.com/cri-o/packaging/$CRIO_SCRIPT_COMMIT/get"
curl -fs "$CRIO_SCRIPT_URL" -o /dev/null || {
    echo "Error: CRIO_SCRIPT_COMMIT in $BASE_PATH/env.yaml is wrong. The get script was not found at: $CRIO_SCRIPT_URL" 1>&2
    exit 1
}

CRIO_COMMIT=$(grep "CRIO_COMMIT" "$BASE_PATH/env.yaml" | sed -rn 's/^.*CRIO_COMMIT=([0-9a-f]+).*$/\1/p')
CRIO_BIN_URL="https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.$CRIO_COMMIT.tar.gz"
curl -fs "$CRIO_BIN_URL" -o /dev/null || {
    echo "Error: CRIO_COMMIT in $BASE_PATH/env.yaml is wrong. The cri-o binary was not found at: $CRIO_BIN_URL" 1>&2
    exit 1
}
