/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package assign

import (
	"fmt"
	"regexp"
	"strings"

	"k8s.io/test-infra/prow/github"
	"k8s.io/test-infra/prow/plugins"
)

const pluginName = "assign"

var (
	assignRe = regexp.MustCompile(`(?mi)^/(un)?assign(( @[-\w]+?)*)\s*\r?$`)
	ccRe     = regexp.MustCompile(`(?mi)^/(un)?cc(( +@[-\w]+?)+)\s*\r?$`)
)

func init() {
	plugins.RegisterIssueCommentHandler(pluginName, handleIssueComment)
	plugins.RegisterIssueHandler(pluginName, handleIssue)
	plugins.RegisterPullRequestHandler(pluginName, handlePullRequest)
}

type githubClient interface {
	AssignIssue(owner, repo string, number int, logins []string) error
	UnassignIssue(owner, repo string, number int, logins []string) error

	RequestReview(org, repo string, number int, logins []string) error
	UnrequestReview(org, repo string, number int, logins []string) error

	CreateComment(owner, repo string, number int, comment string) error
}

type event struct {
	action string
	body   string
	login  string
	org    string
	repo   string
	url    string
	number int
}

func handlePullRequest(pc plugins.PluginClient, pr github.PullRequestEvent) error {
	e := &event{
		action: pr.Action,
		body:   pr.PullRequest.Body,
		login:  pr.PullRequest.User.Login,
		org:    pr.PullRequest.Base.Repo.Owner.Login,
		repo:   pr.PullRequest.Base.Repo.Name,
		url:    pr.PullRequest.HTMLURL,
		number: pr.Number,
	}
	return combineErrors(handle(newAssignHandler(e, pc.GitHubClient)), handle(newReviewHandler(e, pc.GitHubClient)))
}

func handleIssue(pc plugins.PluginClient, i github.IssueEvent) error {
	e := &event{
		action: i.Action,
		body:   i.Issue.Body,
		login:  i.Issue.User.Login,
		org:    i.Repo.Owner.Login,
		repo:   i.Repo.Name,
		url:    i.Issue.HTMLURL,
		number: i.Issue.Number,
	}
	return handle(newAssignHandler(e, pc.GitHubClient))
}

func handleIssueComment(pc plugins.PluginClient, ic github.IssueCommentEvent) error {
	e := &event{
		action: ic.Action,
		body:   ic.Comment.Body,
		login:  ic.Comment.User.Login,
		org:    ic.Repo.Owner.Login,
		repo:   ic.Repo.Name,
		url:    ic.Comment.HTMLURL,
		number: ic.Issue.Number,
	}
	if ic.Issue.IsPullRequest() {
		return combineErrors(handle(newAssignHandler(e, pc.GitHubClient)), handle(newReviewHandler(e, pc.GitHubClient)))
	}
	return handle(newAssignHandler(e, pc.GitHubClient))
}

func parseLogins(text string) []string {
	var parts []string
	for _, p := range strings.Split(text, " ") {
		t := strings.Trim(p, "@ ")
		if t == "" {
			continue
		}
		parts = append(parts, t)
	}
	return parts
}

func combineErrors(err1, err2 error) error {
	if err1 != nil && err2 != nil {
		return fmt.Errorf("two errors: 1)%v 2)%v.", err1, err2)
	} else if err1 != nil {
		return err1
	} else {
		return err2
	}
}

// handle is the generic handler for the assign plugin. It uses the handler's regexp and affectedLogins
// functions to identify the users to add and/or remove and then passes the appropriate users to the
// handler's add and remove functions. If add fails to add some of the users, a response comment is
// created where the body of the response is generated by the handler's addFailureResponse function.
func handle(h *handler) error {
	e := h.event
	if e.action != "created" && e.action != "opened" { // Only consider new comments/issues
		return nil
	}
	matches := h.regexp.FindAllStringSubmatch(e.body, -1)
	if matches == nil {
		return nil
	}
	users := make(map[string]bool)
	for _, re := range matches {
		add := re[1] != "un" // un<cmd> == !add
		for _, login := range h.affectedLogins(re[2]) {
			users[login] = add
		}
	}
	var toAdd, toRemove []string
	for login, add := range users {
		if add {
			toAdd = append(toAdd, login)
		} else {
			toRemove = append(toRemove, login)
		}
	}

	if len(toRemove) > 0 {
		if err := h.remove(e.org, e.repo, e.number, toRemove); err != nil {
			return err
		}
	}
	if len(toAdd) > 0 {
		if err := h.add(e.org, e.repo, e.number, toAdd); err != nil {
			if mu, ok := err.(github.MissingUsers); ok {
				msg := h.addFailureResponse(mu)
				if len(msg) == 0 {
					return nil
				}
				if err := h.gc.CreateComment(e.org, e.repo, e.number, plugins.FormatResponseRaw(e.body, e.url, e.login, msg)); err != nil {
					return fmt.Errorf("comment err: %v", err)
				}
				return nil
			}
			return err
		}
	}
	return nil
}

// handler is a struct that contains data about a github event and provides functions to help handle it.
type handler struct {
	// addFailureResponse generates the body of a response comment in the event that the add function fails.
	addFailureResponse func(mu github.MissingUsers) string
	// remove is the function that is called on the affected logins for a command prefixed with 'un'.
	remove func(org, repo string, number int, users []string) error
	// add is the function that is called on the affected logins for a command with no 'un' prefix.
	add func(org, repo string, number int, users []string) error
	// affectedLogins extracts the user logins that a command is refering to from the command arg string.
	affectedLogins func(argString string) []string

	// event is a pointer to an event struct describing the event that triggered the handler.
	event *event
	// regexp is the regular expression describing the command. It must have an optional 'un' prefix
	// as the first subgroup and the arguments to the command as the second subgroup.
	regexp *regexp.Regexp
	// gc is the githubClient to use for creating response comments in the event of a failure.
	gc githubClient
}

func newAssignHandler(e *event, gc githubClient) *handler {
	addFailureResponse := func(mu github.MissingUsers) string {
		return fmt.Sprintf("GitHub didn't allow me to assign the following users: %s.\n\nNote that only [%s members](https://github.com/orgs/%s/people) can be assigned.", strings.Join(mu.Users, ", "), e.org, e.org)
	}

	affectedLogins := func(text string) []string {
		if text == "" {
			return []string{e.login}
		}
		return parseLogins(text)
	}

	return &handler{
		addFailureResponse: addFailureResponse,
		remove:             gc.UnassignIssue,
		add:                gc.AssignIssue,
		affectedLogins:     affectedLogins,
		event:              e,
		regexp:             assignRe,
		gc:                 gc,
	}
}

func newReviewHandler(e *event, gc githubClient) *handler {
	addFailureResponse := func(mu github.MissingUsers) string {
		return fmt.Sprintf("GitHub didn't allow me to request PR reviews from the following users: %s.\n\nNote that only people with write access to %s/%s can review this PR.\n", strings.Join(mu.Users, ", "), e.org, e.repo)
	}

	return &handler{
		addFailureResponse: addFailureResponse,
		remove:             gc.UnrequestReview,
		add:                gc.RequestReview,
		affectedLogins:     parseLogins,
		event:              e,
		regexp:             ccRe,
		gc:                 gc,
	}
}
