/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package types defines the YAML-serializable types for Prow job and TestGrid
// configurations generated by the generate-tests tool.
package types

// ProwJob represents a Prow periodic job config for YAML output.
// sigs.k8s.io/yaml uses JSON tags for field naming.
type ProwJob struct {
	Tags             []string          `json:"tags"`
	Interval         string            `json:"interval"`
	Labels           map[string]string `json:"labels"`
	Decorate         bool              `json:"decorate"`
	DecorationConfig map[string]string `json:"decoration_config"`
	Name             string            `json:"name"`
	Spec             ProwSpec          `json:"spec"`
	Cluster          string            `json:"cluster"`
	ExtraRefs        []ProwExtraRef    `json:"extra_refs"`
	Annotations      map[string]string `json:"annotations"`
}

// ProwSpec is the spec section of a ProwJob.
type ProwSpec struct {
	Containers []ProwContainer `json:"containers"`
}

// ProwContainer is a container within a ProwSpec.
type ProwContainer struct {
	Command   []string      `json:"command"`
	Args      []string      `json:"args"`
	Image     string        `json:"image"`
	Resources ProwResources `json:"resources"`
}

// ProwResources specifies CPU and memory requests/limits.
type ProwResources struct {
	Requests ProwResourceValues `json:"requests"`
	Limits   ProwResourceValues `json:"limits"`
}

// ProwResourceValues holds CPU and memory values.
type ProwResourceValues struct {
	CPU    string `json:"cpu"`
	Memory string `json:"memory"`
}

// ProwExtraRef is an extra git ref to check out.
type ProwExtraRef struct {
	Org       string `json:"org"`
	Repo      string `json:"repo"`
	BaseRef   string `json:"base_ref"`
	PathAlias string `json:"path_alias"`
}

// ProwConfig is the top-level Prow config with a periodics list.
type ProwConfig struct {
	Periodics []ProwJob `json:"periodics"`
}

// TestGroup represents a TestGrid test group entry.
type TestGroup struct {
	Name         string         `json:"name"`
	GCSPrefix    string         `json:"gcs_prefix"`
	ColumnHeader []ColumnHeader `json:"column_header"`
}

// ColumnHeader is a single column header in a TestGrid test group.
type ColumnHeader struct {
	ConfigurationValue string `json:"configuration_value"`
}

// TestGridConfig is the top-level TestGrid config with test groups.
type TestGridConfig struct {
	TestGroups []TestGroup `json:"test_groups"`
}
