package labels

const LGTM = "lgtm"
const BlockedPaths = "do-not-merge/blocked-paths"
const LifecycleActive = "lifecycle/active"
const LifecycleFrozen = "lifecycle/frozen"
const LifecycleStale = "lifecycle/stale"
const LifecycleRotten = "lifecycle/rotten"
const ClaYes = "cncf-cla: yes"
const ClaNo = "cncf-cla: no"
const Approved = "approved"
const InvalidOwners = "do-not-merge/invalid-owners-file"
const CpUnapproved = "do-not-merge/cherry-pick-not-approved"
const CpApproved = "cherry-pick-approved"
const WorkInProgress = "do-not-merge/work-in-progress"
const Hold = "do-not-merge/hold"
const Shrug = "¯\\_(ツ)_/¯"
const NeedsSig = "needs-sig"
const Bug = "kind/bug"
const Help = "help wanted"
const GoodFirstIssue = "good first issue"
const NeedsRebase = "needs-rebase"
