package labels

const LGTMLabel = "lgtm"
const BlockedPathsLabel = "do-not-merge/blocked-paths"
const LifecycleActiveLabel = "lifecycle/active"
const LifecycleFrozenLabel = "lifecycle/frozen"
const LifecycleStaleLabel = "lifecycle/stale"
const LifecycleRottenLabel = "lifecycle/rotten"
const ClaYesLabel = "cncf-cla: yes"
const ClaNoLabel = "cncf-cla: no"
const ApprovedLabel = "approved"
const InvalidOwnersLabel = "do-not-merge/invalid-owners-file"
const CpUnapprovedLabel = "do-not-merge/cherry-pick-not-approved"
const CpApprovedLabel = "cherry-pick-approved"
const WorkInProgressLabel = "do-not-merge/work-in-progress"
const EvilCodeLabel = "do-not-merge/evil-code"
const HoldLabel = "do-not-merge/hold"
const ShrugLabel = "¯\\_(ツ)_/¯"
const NeedsSigLabel = "needs-sig"
const BugLabel = "kind/bug"
const AwesomeLabel = "sig/awesome"
const HelpLabel = "help wanted"
const GoodFirstIssueLabel = "good first issue"
const NeedsRebaseLabel = "needs-rebase"
