#!/bin/bash

# Copyright 2016 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Compiles a static HTML site containing the last day's worth of test results.

set -o errexit
set -o nounset
set -o xtrace

readonly bucket="kubernetes-test-history"
readonly jsonpath="gs://${bucket}/logs/$(date +%F).json"

# Download previous json report, for faster incremental report generation.
# This will fail when the day rolls over -- meaning a new report will be
# generated.
gsutil -q cp "${jsonpath}" "tests.json" || true

# Create JSON report
time python gen_json.py \
  --buckets=buckets.json \
  "--match=^kubernetes|kubernetes-build|kubelet-gce-e2e-ci"

# Create static HTML reports out of the JSON
python gen_html.py \
    --output-dir=static \
    --input=tests.json \
    --buckets=buckets.json

# Upload to GCS
readonly gcs_acl="public-read"
gsutil -q cp -a "${gcs_acl}" -z json "tests.json" "${jsonpath}"
gsutil -q cp -ra "${gcs_acl}" "static" "gs://${bucket}/"
