{
 "title": "prow dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  {
   "title": "up",
   "type": "graph",
   "description": "sum by(job) (up)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by(job) (up)", "legendFormat": "{{job}}" }
   ]
  }
 ]
}
{
 "title": "deck dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "path",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, path)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, method)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(deck_http_request_duration_seconds_count{job=\"deck\"}, status)"
   }
  ]
 },
 "panels": [
  {
   "title": "median latency with (pre-defined) paths, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"<path>\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/tide\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/tide"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/plugin-help.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/plugin-help.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/prowjobs.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/prowjobs.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/pr-data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/log\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/log"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/rerun\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/rerun"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/spyglass/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/spyglass/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/view/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/view/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/job-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/job-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=\"/pr-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{path=\"others\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "others"
    }
   ]
  },
  {
   "title": "latency percentile with path ${path}, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(<phi>, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "phi=0.5"
    }
   ]
  },
  {
   "title": "traffic: couter by status with path ${path} and method ${method}",
   "type": "graph",
   "description": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m])) by (status)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "status percentage with path ${path} and method ${method}",
   "type": "graph",
   "description": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"n..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\"}[5m]))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"2..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"3..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"4..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", status=~\"5..\", path=~\"$path\", method=~\"$method\"}[5m]))/sum(rate(deck_http_request_duration_seconds_count{job=\"deck\", path=~\"$path\", method=~\"$method\"}[5m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "apdex score with target 2.5s and tolerance 10s, path ${path}, method ${method}, and status ${status}",
   "type": "graph",
   "description": "( sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"2.5\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) + sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"10\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) ) / 2 / sum(rate(deck_http_request_duration_seconds_count{path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"2.5\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) + sum(rate(deck_http_request_duration_seconds_bucket{job=\"deck\", le=\"10\", path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job) ) / 2 / sum(rate(deck_http_request_duration_seconds_count{path=~\"${path}\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (job)"
    }
   ]
  },
  {
   "title": "median response size with (pre-defined) paths, method ${method}, and status ${status}",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"<path>\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/tide\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/tide"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/plugin-help.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/plugin-help.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/prowjobs.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/prowjobs.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/pr-data.js\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-data.js"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/log\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/log"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/rerun\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/rerun"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/spyglass/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/spyglass/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/view/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/view/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/job-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/job-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{job=\"deck\", path=\"/pr-history/\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "/pr-history/"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(deck_http_response_size_bytes_bucket{path=\"others\", method=~\"${method}\", status=~\"${status}\"}[5m])) by (le))",
     "legendFormat": "others"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Cache Requests (per hour)",
   "type": "graph",
   "description": "Count of cache requests of each cache mode over the last hour.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses[1h])) by (mode)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]))",
     "legendFormat": "(No Cost)"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Cache Efficiency",
   "type": "graph",
   "description": "Percentage of cacheable requests that are fulfilled for free.\nNo cost modes are \"COALESCED\" and \"REVALIDATED\".\nCacheable modes include the no cost modes, \"CHANGED\" and \"MISS\".",
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Cacheable Request Fulfilled for Free"
    }
   ],
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h])) \n/ sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED|MISS|CHANGED\"}[1h]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Efficiency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": []
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Disk Usage",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(ghcache_disk_used/(ghcache_disk_used+ghcache_disk_free)) without(instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "% Used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(ghcache_disk_used) without(instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "GB Used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(ghcache_disk_free) without(instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "GB Free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last hour",
   "type": "singlestat",
   "description": "The number of no cost requests in the last hour.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[1h]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Tokens Saved: Last 7 days",
   "type": "singlestat",
   "description": "The number of no cost requests in the last 7 days.\nThis includes both \"COALESCED\" and \"REVALIDATED\" modes.",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ghcache_responses{mode=~\"COALESCED|REVALIDATED\"}[7d]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "hook dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "webhook counter",
   "type": "singlestat",
   "description": "sum(prow_webhook_counter)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(prow_webhook_counter)" }
   ]
  },
  {
   "title": "webhook response codes",
   "type": "singlestat",
   "description": "sum(prow_webhook_response_codes)",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prow_webhook_response_codes)"
    }
   ]
  },
  {
   "title": "incoming webhooks by event type",
   "type": "graph",
   "description": "sum(rate(prow_webhook_counter[1m])) by (event_type)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prow_webhook_counter[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "webhook response codes",
   "type": "graph",
   "description": "sum(rate(prow_webhook_response_codes[1m])) by (response_code)",
   "gridPos": { "h": 9, "w": 24, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prow_webhook_response_codes[1m])) by (response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  }
 ]
}
{
 "title": "plank dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "number of Prow jobs by type",
   "type": "graph",
   "description": "sum(prowjobs{job=\"plank\"}) by (type)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=\"plank\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "number of Prow jobs by state",
   "type": "graph",
   "description": "sum(prowjobs{job=\"plank\"}) by (state)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prowjobs{job=\"plank\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}
{
 "title": "sinker dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "time used in each sinker cleaning",
   "type": "graph",
   "description": "sum(sinker_loop_duration_seconds)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_loop_duration_seconds)"
    }
   ]
  },
  {
   "title": "existing pods/prow jobs",
   "type": "graph",
   "description": "sum(sinker_pods_existing) and sum(sinker_prow_jobs_existing)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sinker_pods_existing)" },
    { "expr": "sum(sinker_prow_jobs_existing)" }
   ]
  },
  {
   "title": "removed pods",
   "type": "graph",
   "description": "sum(sinker_pods_removed) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_pods_removed) by (reason)"
    }
   ]
  },
  {
   "title": "cleaned prow jobs",
   "type": "graph",
   "description": "sum(sinker_prow_jobs_cleaned) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_prow_jobs_cleaned) by (reason)"
    }
   ]
  },
  {
   "title": "errors occurred in pod cleaning",
   "type": "graph",
   "description": "sum(sinker_pod_removal_errors) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_pod_removal_errors) by (reason)"
    }
   ]
  },
  {
   "title": "errors occurred in prow job cleaning",
   "type": "graph",
   "description": "sum(sinker_prow_jobs_cleaning_errors) by (reason)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sinker_prow_jobs_cleaning_errors) by (reason)"
    }
   ]
  }
 ]
}
{
 "title": "tide dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Tide Pool Sizes",
   "type": "graph",
   "description": "The number of PRs eligible for merge in each Tide pool.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(pooledprs and ((time() - updatetime) < 240)) by (org, repo, branch)",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Daily Merge Rate",
   "type": "graph",
   "description": "Calculated on a 24 hour interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(merges_sum[1d]) > 0) by (org, repo, branch)) * 86400",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Daily Merge Rate: Batches Only",
   "type": "graph",
   "description": "Calculated on a 24 hour interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(    rate(merges_sum[1d]) - (sum(rate(merges_bucket{le=\"1\"}[1d])) without (le)) > 0     ) by (org, repo, branch)) * 86400",
     "legendFormat": "{{org}}/{{repo}}:{{branch}}"
    }
   ]
  },
  {
   "title": "Tide Pool: kubernetes/kubernetes:master",
   "type": "graph",
   "description": "Tide stats for the master branch of the kubernetes/kubernetes repo.\nSpecifically, the number of pooled PRs and the daily merge rate.\n(See the more general graphs for details on how these are calculated.)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(pooledprs{org=\"kubernetes\",repo=\"kubernetes\",branch=\"master\"} and ((time() - updatetime) < 240)) or vector(0)",
     "legendFormat": "Pool size"
    },
    {
     "expr": "sum(rate(merges_sum{org=\"kubernetes\",repo=\"kubernetes\",branch=\"master\"}[1d])) * 86400",
     "legendFormat": "Daily merge rate"
    }
   ]
  },
  {
   "title": "Tide Processing Time (seconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(syncdur and (changes(syncdur[1h]) > 0))",
     "legendFormat": "Sync time"
    },
    {
     "expr": "max(statusupdatedur and (changes(statusupdatedur[1h]) > 0))",
     "legendFormat": "Status update time"
    }
   ]
  }
 ]
}