dashboard_groups:
  - name: sig-autoscaling
    dashboard_names:
      - sig-autoscaling-cluster-autoscaler
      - sig-autoscaling-hpa-periodics
      - sig-autoscaling-hpa-presubmits
      - sig-autoscaling-vpa-periodics
      - sig-autoscaling-vpa-presubmits

dashboards:
  - name: sig-autoscaling-cluster-autoscaler
  - name: sig-autoscaling-hpa-periodics
  - name: sig-autoscaling-hpa-presubmits
  - name: sig-autoscaling-vpa-periodics
  - name: sig-autoscaling-vpa-presubmits
