dashboard_groups:
  - name: sig-autoscaling
    dashboard_names:
      - sig-autoscaling-cluster-autoscaler
      - sig-autoscaling-hpa-periodics
      - sig-autoscaling-hpa-presubmits
      - sig-autoscaling-vpa-periodics
      - sig-autoscaling-vpa-presubmits
      - sig-autoscaling-addon-resizer
      - sig-autoscaling-vpa-images
      - sig-autoscaling-cluster-autoscaler-images

dashboards:
  - name: sig-autoscaling-cluster-autoscaler
  - name: sig-autoscaling-hpa-periodics
  - name: sig-autoscaling-hpa-presubmits
  - name: sig-autoscaling-vpa-periodics
  - name: sig-autoscaling-vpa-presubmits
  - name: sig-autoscaling-addon-resizer
  - name: sig-autoscaling-vpa-images
  - name: sig-autoscaling-cluster-autoscaler-images
