dashboard_groups:
- name: conformance
  dashboard_names:
    - conformance-all
    - conformance-apisnoop
    - conformance-ec2
    - conformance-gce
    - conformance-azure
    - conformance-kind
    - conformance-hack-local-up-cluster
    - conformance-ppc64le
    - conformance-gardener
    - conformance-s390x
    - conformance-arm64

dashboards:
- name: conformance-all
  # entries are named $PROVIDER, $KUBERNETES_RELEASE
  dashboard_tab:
    - name: Gardener, v1.35 AWS
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Amazon Web Services (AWS)
      test_group_name: ci-gardener-e2e-conformance-aws-v1.35
    - name: Gardener, v1.35 GCE
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Google Cloud Engine (GCE)
      test_group_name: ci-gardener-e2e-conformance-gce-v1.35
    - name: Gardener, v1.35 OpenStack
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Openstack
      test_group_name: ci-gardener-e2e-conformance-openstack-v1.35
    - name: Gardener, v1.35 Azure
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Microsoft Azure
      test_group_name: ci-gardener-e2e-conformance-azure-v1.35
    - name: Gardener, v1.35 Alibaba Cloud
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Alibaba Cloud
      test_group_name: ci-gardener-e2e-conformance-alicloud-v1.35
    - name: Gardener, v1.34 AWS
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Amazon Web Services (AWS)
      test_group_name: ci-gardener-e2e-conformance-aws-v1.34
    - name: Gardener, v1.34 GCE
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Google Cloud Engine (GCE)
      test_group_name: ci-gardener-e2e-conformance-gce-v1.34
    - name: Gardener, v1.34 OpenStack
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Openstack
      test_group_name: ci-gardener-e2e-conformance-openstack-v1.34
    - name: Gardener, v1.34 Azure
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Microsoft Azure
      test_group_name: ci-gardener-e2e-conformance-azure-v1.34
    - name: Gardener, v1.34 Alibaba Cloud
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Alibaba Cloud
      test_group_name: ci-gardener-e2e-conformance-alicloud-v1.34
    - name: Gardener, v1.33 AWS
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Amazon Web Services (AWS)
      test_group_name: ci-gardener-e2e-conformance-aws-v1.33
    - name: Gardener, v1.33 GCE
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Google Cloud Engine (GCE)
      test_group_name: ci-gardener-e2e-conformance-gce-v1.33
    - name: Gardener, v1.33 OpenStack
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Openstack
      test_group_name: ci-gardener-e2e-conformance-openstack-v1.33
    - name: Gardener, v1.33 Azure
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Microsoft Azure
      test_group_name: ci-gardener-e2e-conformance-azure-v1.33
    - name: Gardener, v1.33 Alibaba Cloud
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Alibaba Cloud
      test_group_name: ci-gardener-e2e-conformance-alicloud-v1.33
    - name: Gardener, v1.32 AWS
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Amazon Web Services (AWS)
      test_group_name: ci-gardener-e2e-conformance-aws-v1.32
    - name: Gardener, v1.32 GCE
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Google Cloud Engine (GCE)
      test_group_name: ci-gardener-e2e-conformance-gce-v1.32
    - name: Gardener, v1.32 OpenStack
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Openstack
      test_group_name: ci-gardener-e2e-conformance-openstack-v1.32
    - name: Gardener, v1.32 Azure
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Microsoft Azure
      test_group_name: ci-gardener-e2e-conformance-azure-v1.32
    - name: Gardener, v1.32 Alibaba Cloud
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Alibaba Cloud
      test_group_name: ci-gardener-e2e-conformance-alicloud-v1.32

- name: conformance-apisnoop
- name: conformance-ec2
- name: conformance-gce
- name: conformance-azure
- name: conformance-hack-local-up-cluster
- name: conformance-ppc64le
- name: conformance-arm64
- name: conformance-kind
- name: conformance-s390x

# Gardener Conformance Dashboard
- name: conformance-gardener
  dashboard_tab:
    - name: Gardener, v1.35 AWS
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Amazon Web Services (AWS)
      test_group_name: ci-gardener-e2e-conformance-aws-v1.35
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.35 GCE
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Google Cloud Engine (GCE)
      test_group_name: ci-gardener-e2e-conformance-gce-v1.35
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.35 OpenStack
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Openstack
      test_group_name: ci-gardener-e2e-conformance-openstack-v1.35
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.35 Azure
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Microsoft Azure
      test_group_name: ci-gardener-e2e-conformance-azure-v1.35
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.35 Alibaba Cloud
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Alibaba Cloud
      test_group_name: ci-gardener-e2e-conformance-alicloud-v1.35
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.34 AWS
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Amazon Web Services (AWS)
      test_group_name: ci-gardener-e2e-conformance-aws-v1.34
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.34 GCE
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Google Cloud Engine (GCE)
      test_group_name: ci-gardener-e2e-conformance-gce-v1.34
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.34 OpenStack
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Openstack
      test_group_name: ci-gardener-e2e-conformance-openstack-v1.34
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.34 Azure
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Microsoft Azure
      test_group_name: ci-gardener-e2e-conformance-azure-v1.34
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.34 Alibaba Cloud
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Alibaba Cloud
      test_group_name: ci-gardener-e2e-conformance-alicloud-v1.34
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.33 AWS
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Amazon Web Services (AWS)
      test_group_name: ci-gardener-e2e-conformance-aws-v1.33
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.33 GCE
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Google Cloud Engine (GCE)
      test_group_name: ci-gardener-e2e-conformance-gce-v1.33
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.33 OpenStack
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Openstack
      test_group_name: ci-gardener-e2e-conformance-openstack-v1.33
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.33 Azure
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Microsoft Azure
      test_group_name: ci-gardener-e2e-conformance-azure-v1.33
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.33 Alibaba Cloud
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Alibaba Cloud
      test_group_name: ci-gardener-e2e-conformance-alicloud-v1.33
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.32 AWS
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Amazon Web Services (AWS)
      test_group_name: ci-gardener-e2e-conformance-aws-v1.32
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.32 GCE
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Google Cloud Engine (GCE)
      test_group_name: ci-gardener-e2e-conformance-gce-v1.32
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.32 OpenStack
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Openstack
      test_group_name: ci-gardener-e2e-conformance-openstack-v1.32
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.32 Azure
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Microsoft Azure
      test_group_name: ci-gardener-e2e-conformance-azure-v1.32
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com
    - name: Gardener, v1.32 Alibaba Cloud
      description: Runs conformance tests on a Kubernetes cluster provided by Gardener (https://github.com/gardener/gardener) on Alibaba Cloud
      test_group_name: ci-gardener-e2e-conformance-alicloud-v1.32
      alert_options:
        alert_mail_to_addresses: gardener-oq@listserv.sap.com

test_groups:

# Gardener Conformance Test Groups
- name: ci-gardener-e2e-conformance-aws-v1.35
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-aws-v1.35
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-gce-v1.35
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-gce-v1.35
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-openstack-v1.35
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-openstack-v1.35
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-azure-v1.35
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-azure-v1.35
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-alicloud-v1.35
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-alicloud-v1.35
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-aws-v1.34
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-aws-v1.34
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-gce-v1.34
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-gce-v1.34
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-openstack-v1.34
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-openstack-v1.34
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-azure-v1.34
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-azure-v1.34
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-alicloud-v1.34
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-alicloud-v1.34
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-aws-v1.33
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-aws-v1.33
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-gce-v1.33
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-gce-v1.33
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-openstack-v1.33
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-openstack-v1.33
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-azure-v1.33
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-azure-v1.33
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-alicloud-v1.33
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-alicloud-v1.33
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-aws-v1.32
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-aws-v1.32
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-gce-v1.32
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-gce-v1.32
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-openstack-v1.32
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-openstack-v1.32
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-azure-v1.32
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-azure-v1.32
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
- name: ci-gardener-e2e-conformance-alicloud-v1.32
  gcs_prefix: k8s-conformance-gardener/ci-gardener-e2e-conformance-alicloud-v1.32
  alert_stale_results_hours: 168
  num_failures_to_alert: 1
  disable_prowjob_analysis: true
