presubmits:
  kubernetes-sigs/node-readiness-controller:
  - name: pull-node-readiness-controller-junit-report-canary
    cluster: eks-prow-build-cluster
    always_run: false
    optional: true
    labels:
      preset-dind-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 2h
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260810-7619858115-master
          command:
            - runner.sh
          env:
          - name: JUNIT_REPORT
            value: "true"
          args:
            - make
            - test-scale
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 3
              memory: 10Gi
            requests:
              cpu: 3
              memory: 10Gi
    annotations:
      testgrid-dashboards: sig-node-node-readiness-controller
      testgrid-num-columns-recent: '30'
      testgrid-create-test-group: 'true'
