# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM alpine:3.12.0

# Google Cloud SDK requires python 2.7.9+ (https://cloud.google.com/python/setup#installing_the_cloud_sdk)
# and curl to download it.
# update_summaries.sh requires bash.
RUN apk add --no-cache python2 bash curl

# Get the Google Cloud SDK
RUN curl -o installer https://sdk.cloud.google.com && \
    bash installer --disable-prompts --install-dir=/ && \
    rm installer

# Link the binaries
RUN ln -s /google-cloud-sdk/bin/* /bin/

# Copy over the triage binary from the previous Cloud Build stage, and the shell script that orchestrates everything
COPY /workspace/builds/triage update_summaries-go.sh /

# Point GOOGLE_APPLICATION_CREDENTIALS at a serviceaccount.json with the necessary permissions.
ENTRYPOINT ["timeout", "10800", "/update_summaries-go.sh"]
