dashboard_groups:
- name: sig-apps
  dashboard_names:
    - sig-apps-agent-sandbox
    - sig-apps-mcp-lifecycle-operator
    - sig-apps-jobset
    - sig-apps-jobset-periodics
    - sig-apps-jobset-presubmits
    - sig-apps-lws
    - sig-apps-lws-presubmits
    - sig-apps-kjob
    - sig-apps-kjob-periodics
    - sig-apps-kjob-presubmits

dashboards:
- name: sig-apps-agent-sandbox
- name: sig-apps-mcp-lifecycle-operator
- name: sig-apps-jobset
- name: sig-apps-jobset-periodics
- name: sig-apps-jobset-presubmits
- name: sig-apps-lws
- name: sig-apps-lws-presubmits
- name: sig-apps-kjob
- name: sig-apps-kjob-periodics
- name: sig-apps-kjob-presubmits
