# Additional pre-submit jobs for CAPI main branch using the kubekins-e2e-v2 image
# These jobs are intentionally
# separate from the generated jobs so that we can validate the new image works
# correctly on main before rolling it out to release branches.
presubmits:
  kubernetes-sigs/cluster-api:
  - name: pull-cluster-api-e2e-main-v2
    cluster: eks-prow-build-cluster
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    decorate: true
    decoration_config:
      timeout: 180m
    always_run: false
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: sigs.k8s.io/cluster-api
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260821-da0c0a29ed-1.36
        args:
          - runner.sh
          - ./hack/scripts/ci/ci-e2e.sh
        env:
          # enable IPV6 in bootstrap image
          - name: "DOCKER_IN_DOCKER_IPV6_ENABLED"
            value: "true"
          - name: GINKGO_LABEL_FILTER
            value: "!Conformance"
          # Ensure required kind images get built.
          - name: KIND_BUILD_IMAGES
            value: "KUBERNETES_VERSION,KUBERNETES_VERSION_LATEST_CI,KUBERNETES_VERSION_UPGRADE_TO,KUBERNETES_VERSION_UPGRADE_FROM"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4000m
            memory: 16Gi
          limits:
            cpu: 4000m
            memory: 16Gi
    annotations:
      testgrid-dashboards: cluster-api-core-main
      testgrid-tab-name: capi-pr-e2e-main-v2
