presubmits:
  kubernetes/contributor-site:
  - name: pull-contributor-site-validate-hugo-modules
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-contribex-contributor-website
      testgrid-tab-name: pull-contributor-site-validate-hugo-modules
    decorate: true
    run_if_changed: '^(go\.mod|go\.sum|hugo\.yaml|hack/update-hugo-modules\.sh|Dockerfile|netlify\.toml)$'
    branches:
    - ^master$
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/k8s-staging-images/contributor-site/k8s-contrib-site-hugo:v20260504-5ae63b7
        command:
        - bash
        args:
        - ./hack/update-hugo-modules.sh
        - --dry-run
        env:
        - name: GOMODCACHE
          value: /tmp/gomod
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
