/*
Copyright 2016 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	TestGroup
	Dashboard
	LinkTemplate
	LinkOptionsTemplate
	DashboardTab
	Configuration
	DefaultConfiguration
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestGroup_TestsName int32

const (
	TestGroup_TESTS_NAME_MIN     TestGroup_TestsName = 0
	TestGroup_TESTS_NAME_IGNORE  TestGroup_TestsName = 1
	TestGroup_TESTS_NAME_REPLACE TestGroup_TestsName = 2
	TestGroup_TESTS_NAME_APPEND  TestGroup_TestsName = 3
)

var TestGroup_TestsName_name = map[int32]string{
	0: "TESTS_NAME_MIN",
	1: "TESTS_NAME_IGNORE",
	2: "TESTS_NAME_REPLACE",
	3: "TESTS_NAME_APPEND",
}
var TestGroup_TestsName_value = map[string]int32{
	"TESTS_NAME_MIN":     0,
	"TESTS_NAME_IGNORE":  1,
	"TESTS_NAME_REPLACE": 2,
	"TESTS_NAME_APPEND":  3,
}

func (x TestGroup_TestsName) String() string {
	return proto.EnumName(TestGroup_TestsName_name, int32(x))
}
func (TestGroup_TestsName) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Specifies a group of tests to gather.
type TestGroup struct {
	// Name of this TestGroup, for mapping dashboard tabs to tests.
	Name string `protobuf:"bytes,1,opt,name=name" yaml:"name,omitempty"`
	// Path to the test result stored in gcs
	GcsPrefix string `protobuf:"bytes,2,opt,name=gcs_prefix,json=gcsPrefix" yaml:"gcs_prefix,omitempty"`
	// Number of days of test results to gather and serve.
	DaysOfResults int32 `protobuf:"varint,3,opt,name=days_of_results,json=daysOfResults" yaml:"days_of_results,omitempty"`
	// What to do with the 'Tests name' configuration value. It can replace the
	// name of the test, be appended to the name of the test, or ignored. If it is
	// ignored, then the name of the tests will be the build target.
	TestsNamePolicy TestGroup_TestsName       `protobuf:"varint,6,opt,name=tests_name_policy,json=testsNamePolicy,enum=TestGroup_TestsName" yaml:"tests_name_policy,omitempty"`
	ColumnHeader    []*TestGroup_ColumnHeader `protobuf:"bytes,9,rep,name=column_header,json=columnHeader" yaml:"column_header,omitempty"`
	// deprecated - always set both of these to 0
	AlertStateResultsHours int32 `protobuf:"varint,11,opt,name=alert_state_results_hours,json=alertStateResultsHours" yaml:"alert_state_results_hours,omitempty"`
	NumFailuresToAlert     int32 `protobuf:"varint,12,opt,name=num_failures_to_alert,json=numFailuresToAlert" yaml:"num_failures_to_alert,omitempty"`
	// deprecated - always set to true
	UseKubernetesClient bool `protobuf:"varint,24,opt,name=use_kubernetes_client,json=useKubernetesClient" yaml:"use_kubernetes_client,omitempty"`
	// deprecated - always set to true
	IsExternal bool `protobuf:"varint,25,opt,name=is_external,json=isExternal" yaml:"is_external,omitempty"`
}

func (m *TestGroup) Reset()                    { *m = TestGroup{} }
func (m *TestGroup) String() string            { return proto.CompactTextString(m) }
func (*TestGroup) ProtoMessage()               {}
func (*TestGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestGroup) GetColumnHeader() []*TestGroup_ColumnHeader {
	if m != nil {
		return m.ColumnHeader
	}
	return nil
}

// Custom column headers for defining extra column-heading rows from values in
// the test result.
type TestGroup_ColumnHeader struct {
	ConfigurationValue string `protobuf:"bytes,3,opt,name=configuration_value,json=configurationValue" yaml:"configuration_value,omitempty"`
}

func (m *TestGroup_ColumnHeader) Reset()                    { *m = TestGroup_ColumnHeader{} }
func (m *TestGroup_ColumnHeader) String() string            { return proto.CompactTextString(m) }
func (*TestGroup_ColumnHeader) ProtoMessage()               {}
func (*TestGroup_ColumnHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Specifies a dashboard.
type Dashboard struct {
	// A list of the tabs on the dashboard.
	DashboardTab []*DashboardTab `protobuf:"bytes,1,rep,name=dashboard_tab,json=dashboardTab" yaml:"dashboard_tab,omitempty"`
	// A name for the Dashboard.
	Name string `protobuf:"bytes,2,opt,name=name" yaml:"name,omitempty"`
}

func (m *Dashboard) Reset()                    { *m = Dashboard{} }
func (m *Dashboard) String() string            { return proto.CompactTextString(m) }
func (*Dashboard) ProtoMessage()               {}
func (*Dashboard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Dashboard) GetDashboardTab() []*DashboardTab {
	if m != nil {
		return m.DashboardTab
	}
	return nil
}

type LinkTemplate struct {
	// The URL template.
	Url string `protobuf:"bytes,1,opt,name=url" yaml:"url,omitempty"`
	// The options templates.
	Options []*LinkOptionsTemplate `protobuf:"bytes,2,rep,name=options" yaml:"options,omitempty"`
}

func (m *LinkTemplate) Reset()                    { *m = LinkTemplate{} }
func (m *LinkTemplate) String() string            { return proto.CompactTextString(m) }
func (*LinkTemplate) ProtoMessage()               {}
func (*LinkTemplate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LinkTemplate) GetOptions() []*LinkOptionsTemplate {
	if m != nil {
		return m.Options
	}
	return nil
}

// A simple key/value pair for link options.
type LinkOptionsTemplate struct {
	// The key for the option. This is not expanded.
	Key string `protobuf:"bytes,1,opt,name=key" yaml:"key,omitempty"`
	// The value for the option. This is expanded the same as the LinkTemplate.
	Value string `protobuf:"bytes,2,opt,name=value" yaml:"value,omitempty"`
}

func (m *LinkOptionsTemplate) Reset()                    { *m = LinkOptionsTemplate{} }
func (m *LinkOptionsTemplate) String() string            { return proto.CompactTextString(m) }
func (*LinkOptionsTemplate) ProtoMessage()               {}
func (*LinkOptionsTemplate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// A single tab on a dashboard.
type DashboardTab struct {
	// The name of the dashboard tab to display in the client.
	Name string `protobuf:"bytes,1,opt,name=name" yaml:"name,omitempty"`
	// The name of the TestGroup specifying the test results for this tab.
	TestGroupName string `protobuf:"bytes,2,opt,name=test_group_name,json=testGroupName" yaml:"test_group_name,omitempty"`
	// Default bug component for manually filing bugs from the dashboard
	BugComponent int32 `protobuf:"varint,3,opt,name=bug_component,json=bugComponent" yaml:"bug_component,omitempty"`
	// Default code search path for changelist search links
	CodeSearchPath string `protobuf:"bytes,4,opt,name=code_search_path,json=codeSearchPath" yaml:"code_search_path,omitempty"`
	// The URL template to visit after clicking on a cell.
	OpenTestTemplate *LinkTemplate `protobuf:"bytes,7,opt,name=open_test_template,json=openTestTemplate" yaml:"open_test_template,omitempty"`
	// The URL template to visit when filing a bug.
	FileBugTemplate *LinkTemplate `protobuf:"bytes,8,opt,name=file_bug_template,json=fileBugTemplate" yaml:"file_bug_template,omitempty"`
	// The URL template to visit when attaching a bug
	AttachBugTemplate *LinkTemplate `protobuf:"bytes,9,opt,name=attach_bug_template,json=attachBugTemplate" yaml:"attach_bug_template,omitempty"`
	// Text to show in the about menu as a link to another view of the results.
	ResultsText string `protobuf:"bytes,10,opt,name=results_text,json=resultsText" yaml:"results_text,omitempty"`
	// The URL template to visit after clicking.
	ResultsUrlTemplate *LinkTemplate `protobuf:"bytes,11,opt,name=results_url_template,json=resultsUrlTemplate" yaml:"results_url_template,omitempty"`
	// The URL template to visit when searching for changelists.
	CodeSearchUrlTemplate *LinkTemplate `protobuf:"bytes,12,opt,name=code_search_url_template,json=codeSearchUrlTemplate" yaml:"code_search_url_template,omitempty"`
}

func (m *DashboardTab) Reset()                    { *m = DashboardTab{} }
func (m *DashboardTab) String() string            { return proto.CompactTextString(m) }
func (*DashboardTab) ProtoMessage()               {}
func (*DashboardTab) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DashboardTab) GetOpenTestTemplate() *LinkTemplate {
	if m != nil {
		return m.OpenTestTemplate
	}
	return nil
}

func (m *DashboardTab) GetFileBugTemplate() *LinkTemplate {
	if m != nil {
		return m.FileBugTemplate
	}
	return nil
}

func (m *DashboardTab) GetAttachBugTemplate() *LinkTemplate {
	if m != nil {
		return m.AttachBugTemplate
	}
	return nil
}

func (m *DashboardTab) GetResultsUrlTemplate() *LinkTemplate {
	if m != nil {
		return m.ResultsUrlTemplate
	}
	return nil
}

func (m *DashboardTab) GetCodeSearchUrlTemplate() *LinkTemplate {
	if m != nil {
		return m.CodeSearchUrlTemplate
	}
	return nil
}

// A service configuration consisting of multiple test groups and dashboards.
type Configuration struct {
	// A list of groups of tests to gather.
	TestGroups []*TestGroup `protobuf:"bytes,1,rep,name=test_groups,json=testGroups" yaml:"test_groups,omitempty"`
	// A list of all of the dashboards for a server.
	Dashboards []*Dashboard `protobuf:"bytes,2,rep,name=dashboards" yaml:"dashboards,omitempty"`
}

func (m *Configuration) Reset()                    { *m = Configuration{} }
func (m *Configuration) String() string            { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()               {}
func (*Configuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Configuration) GetTestGroups() []*TestGroup {
	if m != nil {
		return m.TestGroups
	}
	return nil
}

func (m *Configuration) GetDashboards() []*Dashboard {
	if m != nil {
		return m.Dashboards
	}
	return nil
}

type DefaultConfiguration struct {
	// A default testgroup with default initialization data
	DefaultTestGroup *TestGroup `protobuf:"bytes,1,opt,name=default_test_group,json=defaultTestGroup" yaml:"default_test_group,omitempty"`
	// A default dashboard with default initialization data
	DefaultDashboardTab *DashboardTab `protobuf:"bytes,2,opt,name=default_dashboard_tab,json=defaultDashboardTab" yaml:"default_dashboard_tab,omitempty"`
}

func (m *DefaultConfiguration) Reset()                    { *m = DefaultConfiguration{} }
func (m *DefaultConfiguration) String() string            { return proto.CompactTextString(m) }
func (*DefaultConfiguration) ProtoMessage()               {}
func (*DefaultConfiguration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DefaultConfiguration) GetDefaultTestGroup() *TestGroup {
	if m != nil {
		return m.DefaultTestGroup
	}
	return nil
}

func (m *DefaultConfiguration) GetDefaultDashboardTab() *DashboardTab {
	if m != nil {
		return m.DefaultDashboardTab
	}
	return nil
}

func init() {
	proto.RegisterType((*TestGroup)(nil), "TestGroup")
	proto.RegisterType((*TestGroup_ColumnHeader)(nil), "TestGroup.ColumnHeader")
	proto.RegisterType((*Dashboard)(nil), "Dashboard")
	proto.RegisterType((*LinkTemplate)(nil), "LinkTemplate")
	proto.RegisterType((*LinkOptionsTemplate)(nil), "LinkOptionsTemplate")
	proto.RegisterType((*DashboardTab)(nil), "DashboardTab")
	proto.RegisterType((*Configuration)(nil), "Configuration")
	proto.RegisterType((*DefaultConfiguration)(nil), "DefaultConfiguration")
	proto.RegisterEnum("TestGroup_TestsName", TestGroup_TestsName_name, TestGroup_TestsName_value)
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 844 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x55, 0x5b, 0x8f, 0xe2, 0x36,
	0x14, 0x6e, 0x20, 0xcc, 0x84, 0x43, 0x98, 0xf1, 0x18, 0xd8, 0x66, 0xb7, 0xaa, 0x4a, 0xa9, 0xb4,
	0x42, 0xad, 0x44, 0xd5, 0xe9, 0x4b, 0x57, 0xed, 0xaa, 0xa5, 0x0c, 0x7b, 0x61, 0x77, 0x19, 0x14,
	0x68, 0x5f, 0x2d, 0x13, 0x0c, 0x44, 0x13, 0xe2, 0x28, 0xb6, 0xab, 0x99, 0x5f, 0xd0, 0xbe, 0xf7,
	0x0f, 0x57, 0x76, 0x2e, 0x84, 0x8a, 0x37, 0xfb, 0xfb, 0xbe, 0x73, 0xf1, 0xb9, 0x24, 0xe0, 0x06,
	0x3c, 0xde, 0x86, 0xbb, 0x51, 0x92, 0x72, 0xc9, 0x07, 0x7f, 0x37, 0xa0, 0xb9, 0x62, 0x42, 0xbe,
	0x4d, 0xb9, 0x4a, 0x30, 0x06, 0x3b, 0xa6, 0x07, 0xe6, 0x59, 0x7d, 0x6b, 0xd8, 0xf4, 0xcd, 0x19,
	0x7f, 0x09, 0xb0, 0x0b, 0x04, 0x49, 0x52, 0xb6, 0x0d, 0x1f, 0xbd, 0x9a, 0x61, 0x9a, 0xbb, 0x40,
	0x2c, 0x0c, 0x80, 0x5f, 0xc2, 0xf5, 0x86, 0x3e, 0x09, 0xc2, 0xb7, 0x24, 0x65, 0x42, 0x45, 0x52,
	0x78, 0xf5, 0xbe, 0x35, 0x6c, 0xf8, 0x6d, 0x0d, 0xdf, 0x6f, 0xfd, 0x0c, 0xc4, 0xbf, 0xc1, 0x8d,
	0x64, 0x42, 0x0a, 0xa2, 0x9d, 0x92, 0x84, 0x47, 0x61, 0xf0, 0xe4, 0x5d, 0xf4, 0xad, 0xe1, 0xd5,
	0x6d, 0x77, 0x54, 0x66, 0x60, 0x4e, 0x62, 0x4e, 0x0f, 0xcc, 0xbf, 0x96, 0xc5, 0x71, 0x61, 0xc4,
	0xf8, 0x17, 0x68, 0x07, 0x3c, 0x52, 0x87, 0x98, 0xec, 0x19, 0xdd, 0xb0, 0xd4, 0x6b, 0xf6, 0xeb,
	0xc3, 0xd6, 0xed, 0xe7, 0x15, 0xeb, 0x89, 0xe1, 0xdf, 0x19, 0xda, 0x77, 0x83, 0xca, 0x0d, 0xbf,
	0x82, 0xe7, 0x34, 0x62, 0xa9, 0x24, 0x42, 0x52, 0xc9, 0x8a, 0x5c, 0xc9, 0x9e, 0xab, 0x54, 0x78,
	0x2d, 0x93, 0xf1, 0x33, 0x23, 0x58, 0x6a, 0x3e, 0xcf, 0xfa, 0x9d, 0x66, 0xf1, 0x0f, 0xd0, 0x8b,
	0xd5, 0x81, 0x6c, 0x69, 0x18, 0xa9, 0x94, 0x09, 0x22, 0x39, 0x31, 0x4a, 0xcf, 0x35, 0x66, 0x38,
	0x56, 0x87, 0x37, 0x39, 0xb7, 0xe2, 0x63, 0xcd, 0xe0, 0x5b, 0xe8, 0x29, 0xc1, 0xc8, 0x83, 0x5a,
	0xb3, 0x34, 0x66, 0x92, 0x09, 0x12, 0x44, 0x21, 0x8b, 0xa5, 0xe7, 0xf5, 0xad, 0xa1, 0xe3, 0x77,
	0x94, 0x60, 0x1f, 0x4a, 0x6e, 0x62, 0x28, 0xfc, 0x15, 0xb4, 0x42, 0x41, 0xd8, 0xa3, 0x64, 0x69,
	0x4c, 0x23, 0xef, 0xb9, 0x51, 0x42, 0x28, 0xa6, 0x39, 0xf2, 0xe2, 0x03, 0xb8, 0xd5, 0x07, 0xe2,
	0xef, 0xa1, 0x93, 0xf5, 0x52, 0xa5, 0x54, 0x86, 0x3c, 0x26, 0x7f, 0xd1, 0x48, 0x31, 0x53, 0xfe,
	0xa6, 0x8f, 0x4f, 0xa8, 0x3f, 0x35, 0x33, 0xb3, 0x1d, 0x0b, 0xd5, 0x66, 0xb6, 0x53, 0x43, 0xf5,
	0x01, 0xcb, 0xfa, 0x6e, 0x0a, 0x8c, 0x31, 0x5c, 0xad, 0xa6, 0xcb, 0xd5, 0x92, 0xcc, 0xc7, 0x9f,
	0xa6, 0xe4, 0xd3, 0xfb, 0x39, 0xfa, 0x0c, 0xf7, 0xe0, 0xa6, 0x82, 0xbd, 0x7f, 0x3b, 0xbf, 0xf7,
	0xa7, 0xc8, 0xc2, 0xcf, 0x00, 0x57, 0x60, 0x7f, 0xba, 0xf8, 0x38, 0x9e, 0x4c, 0x51, 0xed, 0x7f,
	0xf2, 0xf1, 0x62, 0x31, 0x9d, 0xdf, 0xa1, 0xfa, 0xcc, 0x76, 0x6c, 0xd4, 0x98, 0xd9, 0x4e, 0x03,
	0x5d, 0xcc, 0x6c, 0xe7, 0x12, 0x39, 0x33, 0xdb, 0x71, 0x50, 0x73, 0x66, 0x3b, 0x80, 0x5a, 0x33,
	0xdb, 0x69, 0x23, 0x6f, 0x66, 0x3b, 0x2f, 0xd0, 0x17, 0x83, 0x25, 0x34, 0xef, 0xa8, 0xd8, 0xaf,
	0x39, 0x4d, 0x37, 0xf8, 0x16, 0xda, 0x9b, 0xe2, 0x42, 0x24, 0x5d, 0x7b, 0x96, 0xe9, 0x75, 0x7b,
	0x54, 0x4a, 0x56, 0x74, 0xed, 0xbb, 0x9b, 0xca, 0xad, 0x1c, 0xde, 0xda, 0x71, 0x78, 0x07, 0x0b,
	0x70, 0x3f, 0x86, 0xf1, 0xc3, 0x8a, 0x1d, 0x92, 0x88, 0x4a, 0x86, 0x11, 0xd4, 0x55, 0x1a, 0xe5,
	0xf3, 0xad, 0x8f, 0x78, 0x04, 0x97, 0x3c, 0xd1, 0x25, 0x12, 0x5e, 0xcd, 0xc4, 0xe8, 0x8e, 0xb4,
	0xc5, 0x7d, 0x86, 0x15, 0x86, 0x7e, 0x21, 0x1a, 0xbc, 0x86, 0xce, 0x19, 0x5e, 0x3b, 0x7e, 0x60,
	0x4f, 0x85, 0xe3, 0x07, 0xf6, 0x84, 0xbb, 0xd0, 0xc8, 0xfa, 0x91, 0xe5, 0x93, 0x5d, 0x06, 0xff,
	0xd8, 0xe0, 0xde, 0x9d, 0xcb, 0xba, 0xba, 0x72, 0x2f, 0xc1, 0x0c, 0x3f, 0xd9, 0xe9, 0xa1, 0x26,
	0x95, 0x47, 0xb5, 0x65, 0x31, 0xea, 0xa6, 0x6d, 0xdf, 0x40, 0x7b, 0xad, 0x76, 0x24, 0xe0, 0x87,
	0x84, 0xc7, 0x7a, 0xba, 0xb2, 0xcd, 0x73, 0xd7, 0x6a, 0x37, 0x29, 0x30, 0x3c, 0x04, 0x14, 0xf0,
	0x0d, 0x23, 0x82, 0xd1, 0x34, 0xd8, 0x93, 0x84, 0xca, 0xbd, 0x67, 0x1b, 0x6f, 0x57, 0x1a, 0x5f,
	0x1a, 0x78, 0x41, 0xe5, 0x1e, 0xff, 0x0c, 0x98, 0x27, 0x2c, 0x26, 0x26, 0xb6, 0xcc, 0x5f, 0xe6,
	0x5d, 0xf6, 0x2d, 0x53, 0xf9, 0x6a, 0x1d, 0x7d, 0xa4, 0x85, 0x7a, 0x7e, 0xca, 0x02, 0xbc, 0x82,
	0x9b, 0x6d, 0x18, 0x31, 0xa2, 0x13, 0x2a, 0x6d, 0x9d, 0x73, 0xb6, 0xd7, 0x5a, 0xf7, 0xbb, 0xda,
	0x95, 0xa6, 0xaf, 0xa1, 0x43, 0xa5, 0xa4, 0xc1, 0xfe, 0xd4, 0xb8, 0x79, 0xce, 0xf8, 0x26, 0x53,
	0x56, 0xcd, 0xbf, 0x06, 0xb7, 0xd8, 0x66, 0xc9, 0x1e, 0xa5, 0x07, 0xe6, 0x71, 0xad, 0x1c, 0x5b,
	0xb1, 0x47, 0x89, 0x7f, 0x85, 0x6e, 0x21, 0x51, 0x69, 0x74, 0x0c, 0xd1, 0x3a, 0x17, 0x02, 0xe7,
	0xd2, 0x3f, 0xd2, 0xa8, 0x8c, 0xf1, 0x06, 0xbc, 0x6a, 0x11, 0x4f, 0x9c, 0xb8, 0xe7, 0x9c, 0xf4,
	0x8e, 0xb5, 0xad, 0xf8, 0x29, 0x17, 0xe1, 0x02, 0x5d, 0x0e, 0xf6, 0xd0, 0x9e, 0x54, 0x77, 0x14,
	0x7f, 0x07, 0xad, 0x63, 0xdb, 0x45, 0x3e, 0xf2, 0x70, 0xfc, 0xbc, 0xf9, 0x50, 0xb6, 0x5f, 0xe0,
	0x6f, 0x01, 0xca, 0xe9, 0x2f, 0x46, 0x17, 0x8e, 0xeb, 0xe1, 0x57, 0xd8, 0xc1, 0xbf, 0x16, 0x74,
	0xef, 0xd8, 0x96, 0xaa, 0x48, 0x9e, 0x46, 0xfc, 0x09, 0xf0, 0x26, 0xc3, 0xc9, 0x31, 0xb2, 0x19,
	0xc5, 0xd3, 0xc0, 0x28, 0x57, 0x1d, 0xff, 0x14, 0x63, 0xe8, 0x15, 0x96, 0xa7, 0x8b, 0x5a, 0xcb,
	0xab, 0x71, 0xb2, 0xa8, 0x9d, 0x5c, 0x5b, 0x05, 0xd7, 0x17, 0xe6, 0x0f, 0xf4, 0xe3, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xe6, 0xee, 0xfe, 0x09, 0x91, 0x06, 0x00, 0x00,
}
