#!/usr/bin/env bash
set -e

# TODO: remove me when all configs are migrated
exit 0

STATUS=$(git status --porcelain)
if [[ -z $STATUS ]]; then
    echo "tree is clean"
else
    echo "tree is dirty, please commit all changes"
    echo ""
    echo "$STATUS"
    git diff
    exit 1
fi
