#! /bin/bash -e
# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The presubmit jobs for the different Kubernetes-CSI repos are all
# the same except for the repo name. As Prow has no way of specifying
# the same job for multiple repos and manually copy-and-paste would be
# tedious, this script is used instead to generate them.

base="$(dirname $0)"

# All kubernetes-csi repos which are part of the hostpath driver example.
# For these repos we generate the full test matrix.
hostpath_example_repos="
csi-driver-host-path
external-attacher
external-provisioner
livenessprobe
node-driver-registrar
"

# kubernetes-csi repos which only need to be tested against a single
# Kubernetes version. They might not even bring up a cluster at all.
single_config_repos="
csi-test
csi-release-tools
csi-lib-utils
external-snapshotter
"

# No Prow support in them yet.
# csi-driver-fibre-channel
# csi-driver-image-populator
# csi-driver-iscsi
# csi-driver-nfs
# csi-lib-fc
# csi-lib-iscsi
# external-resizer

# All branches that do *not* support Prow testing. All new branches
# are expected to have that support, therefore these list should be
# fixed. By blacklisting old branches we can avoid Prow config
# changes each time a new branch gets created.
skip_branches_cluster_driver_registrar='^(release-1.0)$'
skip_branches_csi_lib_utils='^(release-0.1|release-0.2)$'
skip_branches_csi_test='^(release-0.3|release-1.0|saad-ali-patch-1|saad-ali-patch-2|v0.1.0|v0.2.0)$'
skip_branches_external_attacher='^(release-0.2.0|release-0.3.0|release-0.4|release-1.0|saad-ali-patch-1|saad-ali-patch-2|saad-ali-patch-3|v0.1.0)$'
skip_branches_external_provisioner='^(lpabon-patch-1|release-0.2.0|release-0.3.0|release-0.4|release-1.0|saad-ali-patch-1|saad-ali-patch-2|v0.1.0)$'
skip_branches_external_snapshotter='^(errorhandling|k8s_1.12.0-beta.1|release-0.4|release-1.0|revert-72-pvclister|saad-ali-patch-1|saad-ali-patch-2|test-yang|updateSize)$'
skip_branches_livenessprobe='^(re|release-0.4|release-1.0|saad-ali-patch-1|saad-ali-patch-2|saad-ali-patch-3|saad-ali-patch-4)$'
skip_branches_node_driver_registrar='^(release-1.0)$'

skip_branches () {
    eval echo \\\"\$skip_branches_$(echo $1 | tr - _)\\\" | grep -v '""'
}

find "$base" -name '*.yaml' -exec grep -q 'generated by gen-jobs.sh' '{}' \; -delete

# Resource usage of a job depends on whether it needs to build Kubernetes or not.
resources_for_kubernetes () {
    local kubernetes="$1"

    case $kubernetes in master) cat <<EOF
      resources:
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: "9000Mi"
          # during the tests more like 3-20m is used
          cpu: 2000m
EOF
                            ;;
                            *) cat <<EOF
        resources:
          requests:
            cpu: 2000m
EOF
                            ;;
    esac
}

# Combines deployment and Kubernetes version in a job suffix like "1-14-on-kubernetes-1-13".
kubernetes_job_name () {
    local deployment="$1"
    local kubernetes="$2"
    echo "$(echo "$deployment" | tr . -)-on-kubernetes-$(echo "$kubernetes" | tr . - | sed 's/\([0-9]*\)-\([0-9]*\)-\([0-9]*\)/\1-\2/')"
}

for repo in $hostpath_example_repos; do
    mkdir -p "$base/$repo"
    cat >"$base/$repo/$repo-config.yaml" <<EOF
# generated by gen-jobs.sh, do not edit manually

presubmits:
  kubernetes-csi/$repo:
EOF

    for deployment in 1.13 1.14; do # must have a deploy/kubernetes-<version> dir in csi-driver-host-path
        for kubernetes in 1.13.3 1.14.0; do # these versions must have pre-built kind images (see https://hub.docker.com/r/kindest/node/tags)
            # We could generate these pre-submit jobs for all combinations, but to save resources in the Prow
            # cluster we only do it for those cases where the deployment matches the Kubernetes version.
            # Once we have more than two supported Kubernetes releases we should limit this to the most
            # recent two.
            #
            # Periodic jobs need to test the full matrix.
            if echo "$kubernetes" | grep -q "^$deployment"; then
                cat >>"$base/$repo/$repo-config.yaml" <<EOF
  - name: pull-sig-storage-$repo-$(kubernetes_job_name $deployment $kubernetes)
    # Experimental job, explicitly needs to be started with /test.
    # This can be enabled once the components have the necessary configuration
    # for this combination of deployment+Kubernetes.
    always_run: false
    decorate: true
    skip_report: false
    skip_branches: [$(skip_branches $repo)]
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      # We need this image because it has Docker in Docker and go.
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master
        command:
        - runner.sh
        args:
        - ./.prow.sh
        env:
        # We pick some version for which there are pre-built images for kind.
        # Update only when the newer version is known to not cause issues,
        # otherwise presubmit jobs may start to fail for reasons that are
        # unrelated to the PR. Testing against the latest Kubernetes is covered
        # by periodic jobs (see https://k8s-testgrid.appspot.com/sig-storage-csi#Summary).
        - name: CSI_PROW_KUBERNETES_VERSION
          value: "$kubernetes"
        - name: CSI_PROW_KUBERNETES_DEPLOYMENT
          value: "$deployment"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
$(resources_for_kubernetes "$kubernetes")
EOF
            fi
        done

        cat >>"$base/$repo/$repo-config.yaml" <<EOF
  - name: pull-sig-storage-$repo-$(kubernetes_job_name $deployment master)
    # Experimental job, explicitly needs to be started with /test.
    # This cannot be enabled by default because there's always the risk
    # that something changes in master which breaks the pre-merge check.
    always_run: false
    decorate: true
    skip_report: false
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      # We need this image because it has Docker in Docker and go.
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master
        command:
        - runner.sh
        args:
        - ./.prow.sh
        env:
        - name: CSI_PROW_KUBERNETES_VERSION
          value: "latest"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
$(resources_for_kubernetes master)
EOF
    done
done

for repo in $single_config_repos; do
    mkdir -p "$base/$repo"
    cat >"$base/$repo/$repo-config.yaml" <<EOF
# generated by gen-jobs.sh, do not edit manually

presubmits:
  kubernetes-csi/$repo:
EOF

    cat >>"$base/$repo/$repo-config.yaml" <<EOF
  - name: pull-sig-storage-$repo
    # Experimental job, explicitly needs to be started with /test.
    # This can be enabled once the components have the necessary configuration
    # for this combination of deployment+Kubernetes.
    always_run: false
    decorate: true
    skip_report: false
    skip_branches: [$(skip_branches $repo)]
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      # We need this image because it has Docker in Docker and go.
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master
        command:
        - runner.sh
        args:
        - ./.prow.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
$(resources_for_kubernetes default)
EOF
done

# The csi-driver-host-path repo contains different deployments. We
# test those against different Kubernetes releases at regular
# intervals to detect regressions in Kubernetes. Should not happen as
# Kubernetes itself (at least currently) runs the same tests, but
# better safe than sorry...
cat >>"$base/csi-driver-host-path/csi-driver-host-path-config.yaml" <<EOF

periodics:
EOF

for deployment in 1.13 1.14; do
    for kubernetes in 1.13 1.14 master; do
        # We allow alpha feature testing in all combinations for
        # periodic jobs. This is not guaranteed to work. If it starts
        # breaking due to API changes in Kubernetes, we must update
        # the configuration either here or in csi-release-tools (TBD).
        actual="$(if [ "$kubernetes" = "master" ]; then echo latest; else echo "release-$kubernetes"; fi)"
        cat >>"$base/csi-driver-host-path/csi-driver-host-path-config.yaml" <<EOF
- interval: 6h
  name: ci-kubernetes-csi-$(kubernetes_job_name $deployment $kubernetes)
  decorate: true
  extra_refs:
  # TODO: replace with kubernetes-csi/csi-driver-host-path master once branch prow is merged
  - org: pohly
    repo: csi-driver-host-path
    base_ref: prow
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "$(if [ "$kubernetes" = "master" ]; then echo true; else echo false; fi)"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    # We need this image because it has Docker in Docker and go.
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master
      command:
      - runner.sh
      args:
      - ./.prow.sh
      env:
      - name: CSI_PROW_KUBERNETES_VERSION
        value: "$actual"
      - name: CSI_PROW_BUILD_JOB
        value: "false"
      - name: CSI_PROW_DEPLOYMENT
        value: "kubernetes-$deployment"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
$(resources_for_kubernetes "$actual")
EOF
    done
done

# The canary builds use the latest sidecars from master and run them on
# specific Kubernetes versions, using the deployments for that Kubernetes
# release.
for kubernetes in 1.13 1.14 master; do
    actual="${kubernetes/master/latest}"
    cat >>"$base/csi-driver-host-path/csi-driver-host-path-config.yaml" <<EOF
- interval: 6h
  name: ci-kubernetes-csi-$(kubernetes_job_name canary $kubernetes)
  decorate: true
  extra_refs:
  # TODO: replace with kubernetes-csi/csi-driver-host-path master once branch prow is merged
  - org: pohly
    repo: csi-driver-host-path
    base_ref: prow
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    # We need this image because it has Docker in Docker and go.
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master
      command:
      - runner.sh
      args:
      - ./.prow.sh
      env:
      - name: CSI_PROW_KUBERNETES_VERSION
        value: "$actual"
      - name: CSI_PROW_BUILD_JOB
        value: "false"
      - name: CSI_PROW_DEPLOYMENT
        value: "kubernetes-$deployment"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
$(resources_for_kubernetes "$actual")
EOF
done

# This job can eventually get replaced by the generated job above.
cat >>"$base/csi-lib-utils/csi-lib-utils-config.yaml" <<EOF
  - name: pull-sig-storage-csi-lib-utils-stable
    always_run: true
    decorate: true
    skip_report: false
    spec:
      containers:
      # This image was chosen over the more often used kubekins-e2e because
      # it is smaller and has everything we need (basically just a Go environment).
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20180927-6b4facbe6
        command:
        - make
        args:
        - -k # report as many failures as possible (if any) before finally failing
        - all # build...
        - test # ... and test
EOF
