#!/usr/bin/env bash
# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

if [ ! -e test-infra ]; then
  git clone https://github.com/kubernetes/test-infra
fi

if [ ! -e kubernetes-anywhere ]; then
  git clone https://github.com/kubernetes/kubernetes-anywhere
fi

# This is required until https://github.com/kubernetes/kubernetes-anywhere/issues/332
# is implemented.
if [ ! -e kubernetes-anywhere/phase1/gce/account.json ]; then
  ln -s "${GOOGLE_APPLICATION_CREDENTIALS}" kubernetes-anywhere/phase1/gce/account.json
fi

./test-infra/jenkins/bootstrap.py \
    --repo="k8s.io/${REPO_NAME}" \
    --job="${JOB_NAME}" \
    --service-account="${GOOGLE_APPLICATION_CREDENTIALS}" \
    "$@"
