periodics:
- name: periodic-agent-sandbox-perf-load-test
  cluster: eks-prow-build-cluster
  interval: 6h
  decorate: true
  annotations:
    testgrid-dashboards: sig-apps-agent-sandbox
  extra_refs:
  - org: kubernetes-sigs
    repo: agent-sandbox
    base_ref: main
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260706-7056f81a85-master
      command:
      - runner.sh
      - dev/ci/periodics/test-load-test
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7
          memory: 14Gi
        limits:
          cpu: 7
          memory: 14Gi
- name: periodic-agent-sandbox-migration-test
  cluster: eks-prow-build-cluster
  interval: 1h
  decorate: true
  decoration_config:
    timeout: 30m
  annotations:
    testgrid-dashboards: sig-apps-agent-sandbox
  extra_refs:
  - org: kubernetes-sigs
    repo: agent-sandbox
    base_ref: main
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    - image: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20260706-7056f81a85-master
      command:
      - runner.sh
      - dev/ci/periodics/test-migration
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7
          memory: 14Gi
        limits:
          cpu: 7
          memory: 14Gi
