periodics:
- name: periodic-cluster-api-provider-azure-conformance-v1beta1-release-1-21
  cluster: eks-prow-build-cluster
  decorate: true
  decoration_config:
    timeout: 4h
  minimum_interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-community: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.23
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    serviceAccountName: azure
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20260316-e86cefa561-1.32
        command:
          - runner.sh
        args:
          - ./scripts/ci-conformance.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 6
            memory: "9Gi"
          requests:
            cpu: 6
            memory: "9Gi"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-conformance-v1beta1-release-1-21
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
    description: Runs conformance & node conformance tests on a stable k8s version with cluster-api-provider-azure release-1.23 (v1beta1)
# TODO: Add back N-2 periodic-cluster-api-provider-azure-conformance-v1beta1-with-ci-artifacts once CAPZ 1.23
# releases. periodic-cluster-api-provider-azure-conformance-v1beta1-with-ci-artifacts-release-1-21 was removed
# due to the old CAPI version being incompatible with k8s 1.36+
- name: periodic-cluster-api-provider-azure-capi-e2e-v1beta1-release-1-21
  cluster: eks-prow-build-cluster
  decorate: true
  decoration_config:
    timeout: 4h
  minimum_interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-community: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.23
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    serviceAccountName: azure
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20260316-e86cefa561-1.32
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: "Cluster API E2E tests"
        - name: GINKGO_SKIP
          value: "\\[K8s-Upgrade\\]|API Version Upgrade"
      resources:
        limits:
          cpu: 6
          memory: "9Gi"
        requests:
          cpu: 6
          memory: "9Gi"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-capi-e2e-v1beta1-release-1-21
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
    description: Runs Cluster API E2E tests on cluster-api-provider-azure release-1.23 (v1beta1)
- name: periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-21
  cluster: eks-prow-build-cluster
  decorate: true
  decoration_config:
    timeout: 4h
  minimum_interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-community: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.23
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    serviceAccountName: azure
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20260316-e86cefa561-1.32
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: "Workload cluster creation"
        - name: GINKGO_SKIP
          value: \[Managed Kubernetes\]
      resources:
        limits:
          cpu: 6
          memory: "9Gi"
        requests:
          cpu: 6
          memory: "9Gi"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-e2e-v1beta1-release-1-21
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
    description: Runs Cluster API Provider Azure E2E tests on cluster-api-provider-azure release-1.23 (v1beta1)
- name: periodic-cluster-api-provider-azure-e2e-aks-v1beta1-release-1-21
  cluster: eks-prow-build-cluster
  decorate: true
  decoration_config:
    timeout: 4h
  minimum_interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-community: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.23
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    serviceAccountName: azure
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20260316-e86cefa561-1.32
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: \[Managed Kubernetes\]
        - name: GINKGO_SKIP
          value: ""
      resources:
        limits:
          cpu: 6
          memory: "9Gi"
        requests:
          cpu: 6
          memory: "9Gi"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-e2e-aks-v1beta1-release-1-21
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
    description: Runs managed Kubernetes E2E tests on cluster-api-provider-azure release-1.23 (v1beta1)
